language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source
  - cp .env.example .env

script:
  ## LINT
  - find app -type f -name \*.php -exec php -l {} \;
  ## PHP_CodeSniffer
  - vendor/bin/phpcs --standard=PSR2 app
  ## PHP Copy/Paste Detector
  - vendor/bin/phpcpd --verbose --exclude vendor app
  ## PHPLOC
  - vendor/bin/phploc app
  ## PHPUNIT
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
