language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 app && cp .env.example .env && vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)